name: Build

on:
  push:
  workflow_dispatch:

jobs:
  package:
    name: Python Package
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Prepare Python env
      run: |
        pip install -U pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install packages
      run: |
        pip install .

    - name: Create package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: python-gui-sample-package
        path: |
          dist/*.tar.gz
          dist/*.whl

  executable:
    name: Executable

    strategy:
      fail-fast: false
      matrix:
        os:
        - 'macos-latest'
        - 'ubuntu-latest'
        - 'windows-latest'
        variant:
        - 'pygui-pyside'
        - 'pygui-tkinter'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Prepare Python env
      run: |
        pip install -U pip setuptools wheel

    - name: Install PyInstaller (6.14.2)
      run: |
        pip install -U pyinstaller==6.14.2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install packages
      run: |
        pip install .

    - name: Create executable
      run: |
        cd app
        pyinstaller --noconfirm --clean ${{ matrix.variant }}.spec

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: python-gui-sample-executable-${{ matrix.os }}-${{ matrix.variant }}
        path:
          app/dist/*
